---
version: '3'
services:
  web:
    env_file:
      - ../configs/dev.env
    build:
      context: ./..
      dockerfile: ./deployments/web.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../cmd:/app/cmd
    healthcheck:
      test: curl --fail http://localhost:8080/health-check || exit 1
      interval: 20s
      timeout: 10s
      retries: 1
    depends_on:
      - postgres
  postgres:
    image: "postgres:15"
    env_file:
      - ../configs/dev.env
    ports:
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
