// Code generated by MockGen. DO NOT EDIT.
// Source: vehicle.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/raffops/gofipe/cmd/goFipe/domain"
)

// MockVehicleService is a mock of VehicleService interface.
type MockVehicleService struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleServiceMockRecorder
}

// MockVehicleServiceMockRecorder is the mock recorder for MockVehicleService.
type MockVehicleServiceMockRecorder struct {
	mock *MockVehicleService
}

// NewMockVehicleService creates a new mock instance.
func NewMockVehicleService(ctrl *gomock.Controller) *MockVehicleService {
	mock := &MockVehicleService{ctrl: ctrl}
	mock.recorder = &MockVehicleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleService) EXPECT() *MockVehicleServiceMockRecorder {
	return m.recorder
}

// GetVehicleByFipeCode mocks base method.
func (m *MockVehicleService) GetVehicleByFipeCode(arg0 int) ([]domain.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicleByFipeCode", arg0)
	ret0, _ := ret[0].([]domain.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicleByFipeCode indicates an expected call of GetVehicleByFipeCode.
func (mr *MockVehicleServiceMockRecorder) GetVehicleByFipeCode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicleByFipeCode", reflect.TypeOf((*MockVehicleService)(nil).GetVehicleByFipeCode), arg0)
}

// GetVehicleByReferenceMonth mocks base method.
func (m *MockVehicleService) GetVehicleByReferenceMonth(arg0 int) ([]domain.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicleByReferenceMonth", arg0)
	ret0, _ := ret[0].([]domain.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicleByReferenceMonth indicates an expected call of GetVehicleByReferenceMonth.
func (mr *MockVehicleServiceMockRecorder) GetVehicleByReferenceMonth(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicleByReferenceMonth", reflect.TypeOf((*MockVehicleService)(nil).GetVehicleByReferenceMonth), arg0)
}

// MockVehicleRepository is a mock of VehicleRepository interface.
type MockVehicleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleRepositoryMockRecorder
}

// MockVehicleRepositoryMockRecorder is the mock recorder for MockVehicleRepository.
type MockVehicleRepositoryMockRecorder struct {
	mock *MockVehicleRepository
}

// NewMockVehicleRepository creates a new mock instance.
func NewMockVehicleRepository(ctrl *gomock.Controller) *MockVehicleRepository {
	mock := &MockVehicleRepository{ctrl: ctrl}
	mock.recorder = &MockVehicleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleRepository) EXPECT() *MockVehicleRepositoryMockRecorder {
	return m.recorder
}

// GetVehicleByFipeCode mocks base method.
func (m *MockVehicleRepository) GetVehicleByFipeCode(arg0 int) ([]domain.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicleByFipeCode", arg0)
	ret0, _ := ret[0].([]domain.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicleByFipeCode indicates an expected call of GetVehicleByFipeCode.
func (mr *MockVehicleRepositoryMockRecorder) GetVehicleByFipeCode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicleByFipeCode", reflect.TypeOf((*MockVehicleRepository)(nil).GetVehicleByFipeCode), arg0)
}

// GetVehicleByReferenceMonth mocks base method.
func (m *MockVehicleRepository) GetVehicleByReferenceMonth(arg0 int) ([]domain.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicleByReferenceMonth", arg0)
	ret0, _ := ret[0].([]domain.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicleByReferenceMonth indicates an expected call of GetVehicleByReferenceMonth.
func (mr *MockVehicleRepositoryMockRecorder) GetVehicleByReferenceMonth(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicleByReferenceMonth", reflect.TypeOf((*MockVehicleRepository)(nil).GetVehicleByReferenceMonth), arg0)
}
