// Code generated by MockGen. DO NOT EDIT.
// Source: vehicle.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/raffops/gofipe/cmd/goFipe/domain"
	errs "github.com/raffops/gofipe/cmd/goFipe/errs"
)

// MockVehicleService is a mock of VehicleService interface.
type MockVehicleService struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleServiceMockRecorder
}

// MockVehicleServiceMockRecorder is the mock recorder for MockVehicleService.
type MockVehicleServiceMockRecorder struct {
	mock *MockVehicleService
}

// NewMockVehicleService creates a new mock instance.
func NewMockVehicleService(ctrl *gomock.Controller) *MockVehicleService {
	mock := &MockVehicleService{ctrl: ctrl}
	mock.recorder = &MockVehicleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleService) EXPECT() *MockVehicleServiceMockRecorder {
	return m.recorder
}

// GetVehicleByFipeCode mocks base method.
func (m *MockVehicleService) GetVehicleByFipeCode(fipeCode int, orderBy []domain.OrderBy, pagination domain.Pagination) ([]domain.Vehicle, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicleByFipeCode", fipeCode, orderBy, pagination)
	ret0, _ := ret[0].([]domain.Vehicle)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// GetVehicleByFipeCode indicates an expected call of GetVehicleByFipeCode.
func (mr *MockVehicleServiceMockRecorder) GetVehicleByFipeCode(fipeCode, orderBy, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicleByFipeCode", reflect.TypeOf((*MockVehicleService)(nil).GetVehicleByFipeCode), fipeCode, orderBy, pagination)
}

// GetVehicleByReferenceYearMonth mocks base method.
func (m *MockVehicleService) GetVehicleByReferenceYearMonth(year, month int, orderBy []domain.OrderBy, pagination domain.Pagination) ([]domain.Vehicle, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicleByReferenceYearMonth", year, month, orderBy, pagination)
	ret0, _ := ret[0].([]domain.Vehicle)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// GetVehicleByReferenceYearMonth indicates an expected call of GetVehicleByReferenceYearMonth.
func (mr *MockVehicleServiceMockRecorder) GetVehicleByReferenceYearMonth(year, month, orderBy, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicleByReferenceYearMonth", reflect.TypeOf((*MockVehicleService)(nil).GetVehicleByReferenceYearMonth), year, month, orderBy, pagination)
}

// InsertVehicles mocks base method.
func (m *MockVehicleService) InsertVehicles(arg0 []domain.Vehicle, arg1 *errs.AppError) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InsertVehicles", arg0, arg1)
}

// InsertVehicles indicates an expected call of InsertVehicles.
func (mr *MockVehicleServiceMockRecorder) InsertVehicles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVehicles", reflect.TypeOf((*MockVehicleService)(nil).InsertVehicles), arg0, arg1)
}

// MockVehicleRepository is a mock of VehicleRepository interface.
type MockVehicleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleRepositoryMockRecorder
}

// MockVehicleRepositoryMockRecorder is the mock recorder for MockVehicleRepository.
type MockVehicleRepositoryMockRecorder struct {
	mock *MockVehicleRepository
}

// NewMockVehicleRepository creates a new mock instance.
func NewMockVehicleRepository(ctrl *gomock.Controller) *MockVehicleRepository {
	mock := &MockVehicleRepository{ctrl: ctrl}
	mock.recorder = &MockVehicleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleRepository) EXPECT() *MockVehicleRepositoryMockRecorder {
	return m.recorder
}

// GetVehicle mocks base method.
func (m *MockVehicleRepository) GetVehicle(conditions []domain.Condition, orderBy []domain.OrderBy, pagination domain.Pagination) ([]domain.Vehicle, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicle", conditions, orderBy, pagination)
	ret0, _ := ret[0].([]domain.Vehicle)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// GetVehicle indicates an expected call of GetVehicle.
func (mr *MockVehicleRepositoryMockRecorder) GetVehicle(conditions, orderBy, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicle", reflect.TypeOf((*MockVehicleRepository)(nil).GetVehicle), conditions, orderBy, pagination)
}

// InsertVehicles mocks base method.
func (m *MockVehicleRepository) InsertVehicles(arg0 []domain.Vehicle) *errs.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVehicles", arg0)
	ret0, _ := ret[0].(*errs.AppError)
	return ret0
}

// InsertVehicles indicates an expected call of InsertVehicles.
func (mr *MockVehicleRepositoryMockRecorder) InsertVehicles(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVehicles", reflect.TypeOf((*MockVehicleRepository)(nil).InsertVehicles), arg0)
}
